version: "3.8"
services:
  app:
    image: ep-esi-front
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    ports:
      - 3000:3000
    volumes:
      - "./:/usr/src/app:delegated"
      - /usr/src/app/node_modules